### ISSUE TITLE
Assembly instruction

### ISSUE THREAD

**Issue by Pentizuki** [Audiotronix/Positron_LT#11]
Hello, I´d like to try to build the Positron LT, but it´s kinda hard to comprehend  the whole building-process. Would you mind adding some pictures and/or further instructions on how to assemble this whole thing?
Thanks a lot in advance!

Sincerely
Pentizuki

**Comment by Audiotronix** [comment]
https://github.com/Audiotronix/Positron_LT/blob/instructions-dev/Assembly/README.md


Further instructions coming soon.

For help, pictures and additionall stuff join the Positron_LT discord. 

https://discord.gg/HJ44ZeGG2F

Link is also on main page
