### ISSUE TITLE
Why is the hotend limited to 250C?

### ISSUE THREAD

**Issue by kozross** [Audiotronix/Positron_LT#6]
Is it PTFE-lined or something? If so, that's quite disappointing, as it severely limits what materials can be printed.

**Comment by Audiotronix** [comment]
Because its just a Mod of KRALYNS  Positron V3 which is limited to 250, like u know
But yeah, u are completly right, u are also limited by Bed Temperatur for Materials. 
The Phaetus Hotend, we are all waiting for, is not released yet.

And everything is still work in progress :-)
